/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/index.page').routeMeta;
    };
    '/2022-12-27-my-first-post': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/2022-12-31-my-second-post': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/about': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/archived': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/archived/2022-01-08-post1-2024': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/archived/2022-01-10-post2-2024': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/blog': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/contact': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/archived/[slug]': {
      params: { slug: string };
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/archived/[slug].page').routeMeta;
    };
    '/blog/[slug]': {
      params: { slug: string };
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/blog/[slug].page').routeMeta;
    };
    '/[...page-not-found]': {
      params: { 'page-not-found': string[] };
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
