// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/2022-12-27-my-first-post': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/2022-12-31-my-second-post': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/about': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/about-me': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/another-test': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/archived': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/archived/2022-01-08-post1-2024': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/archived/2022-01-10-post2-2024': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/blog': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/contact': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/shared-test': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/test': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/archived/[slug]': {
      params: { slug: string };
      paramsOutput: { slug: string };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/blog/[slug]': {
      params: { slug: string };
      paramsOutput: { slug: string };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/blog/posts/[slug]': {
      params: { slug: string };
      paramsOutput: { slug: string };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/[...page-not-found]': {
      params: { 'page-not-found': string[] };
      paramsOutput: { 'page-not-found': string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/index": AnalogGeneratedRouteRecord<"/index", "/", "/", null, readonly []>;
  "/2022-12-27-my-first-post": AnalogGeneratedRouteRecord<"/2022-12-27-my-first-post", "2022-12-27-my-first-post", "/2022-12-27-my-first-post", null, readonly []>;
  "/2022-12-31-my-second-post": AnalogGeneratedRouteRecord<"/2022-12-31-my-second-post", "2022-12-31-my-second-post", "/2022-12-31-my-second-post", null, readonly []>;
  "/about": AnalogGeneratedRouteRecord<"/about", "about", "/about", null, readonly []>;
  "/about-me": AnalogGeneratedRouteRecord<"/about-me", "about-me", "/about-me", null, readonly []>;
  "/another-test": AnalogGeneratedRouteRecord<"/another-test", "another-test", "/another-test", null, readonly []>;
  "/archived/index": AnalogGeneratedRouteRecord<"/archived/index", "archived", "/archived", null, readonly ["/archived/2022-01-08-post1-2024", "/archived/2022-01-10-post2-2024", "/archived/[slug]"]>;
  "/archived/2022-01-08-post1-2024": AnalogGeneratedRouteRecord<"/archived/2022-01-08-post1-2024", "2022-01-08-post1-2024", "/archived/2022-01-08-post1-2024", "/archived/index", readonly []>;
  "/archived/2022-01-10-post2-2024": AnalogGeneratedRouteRecord<"/archived/2022-01-10-post2-2024", "2022-01-10-post2-2024", "/archived/2022-01-10-post2-2024", "/archived/index", readonly []>;
  "/blog/index": AnalogGeneratedRouteRecord<"/blog/index", "blog", "/blog", null, readonly ["/blog/[slug]", "/blog/posts/[slug]"]>;
  "/contact": AnalogGeneratedRouteRecord<"/contact", "contact", "/contact", null, readonly []>;
  "/shared-test": AnalogGeneratedRouteRecord<"/shared-test", "shared-test", "/shared-test", null, readonly []>;
  "/test": AnalogGeneratedRouteRecord<"/test", "test", "/test", null, readonly []>;
  "/archived/[slug]": AnalogGeneratedRouteRecord<"/archived/[slug]", "[slug]", "/archived/[slug]", "/archived/index", readonly []>;
  "/blog/[slug]": AnalogGeneratedRouteRecord<"/blog/[slug]", "[slug]", "/blog/[slug]", "/blog/index", readonly []>;
  "/blog/posts/[slug]": AnalogGeneratedRouteRecord<"/blog/posts/[slug]", "posts/[slug]", "/blog/posts/[slug]", "/blog/index", readonly []>;
  "/[...page-not-found]": AnalogGeneratedRouteRecord<"/[...page-not-found]", "[...page-not-found]", "/[...page-not-found]", null, readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/index"];
  "/2022-12-27-my-first-post": AnalogFileRoutesById["/2022-12-27-my-first-post"];
  "/2022-12-31-my-second-post": AnalogFileRoutesById["/2022-12-31-my-second-post"];
  "/about": AnalogFileRoutesById["/about"];
  "/about-me": AnalogFileRoutesById["/about-me"];
  "/another-test": AnalogFileRoutesById["/another-test"];
  "/archived": AnalogFileRoutesById["/archived/index"];
  "/archived/2022-01-08-post1-2024": AnalogFileRoutesById["/archived/2022-01-08-post1-2024"];
  "/archived/2022-01-10-post2-2024": AnalogFileRoutesById["/archived/2022-01-10-post2-2024"];
  "/blog": AnalogFileRoutesById["/blog/index"];
  "/contact": AnalogFileRoutesById["/contact"];
  "/shared-test": AnalogFileRoutesById["/shared-test"];
  "/test": AnalogFileRoutesById["/test"];
  "/archived/[slug]": AnalogFileRoutesById["/archived/[slug]"];
  "/blog/[slug]": AnalogFileRoutesById["/blog/[slug]"];
  "/blog/posts/[slug]": AnalogFileRoutesById["/blog/posts/[slug]"];
  "/[...page-not-found]": AnalogFileRoutesById["/[...page-not-found]"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/index": {
      id: "/index",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/index"],
    "/2022-12-27-my-first-post": {
      id: "/2022-12-27-my-first-post",
      path: "2022-12-27-my-first-post",
      fullPath: "/2022-12-27-my-first-post",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/content/2022-12-27-my-first-post.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/2022-12-27-my-first-post"],
    "/2022-12-31-my-second-post": {
      id: "/2022-12-31-my-second-post",
      path: "2022-12-31-my-second-post",
      fullPath: "/2022-12-31-my-second-post",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/content/2022-12-31-my-second-post.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/2022-12-31-my-second-post"],
    "/about": {
      id: "/about",
      path: "about",
      fullPath: "/about",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/about.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/about"],
    "/about-me": {
      id: "/about-me",
      path: "about-me",
      fullPath: "/about-me",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/about-me.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/about-me"],
    "/another-test": {
      id: "/another-test",
      path: "another-test",
      fullPath: "/another-test",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/content/another-test.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/another-test"],
    "/archived/index": {
      id: "/archived/index",
      path: "archived",
      fullPath: "/archived",
      parentId: null,
      children: ["/archived/2022-01-08-post1-2024", "/archived/2022-01-10-post2-2024", "/archived/[slug]"] as const,
      sourceFile: "/src/app/pages/archived/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/archived/index"],
    "/archived/2022-01-08-post1-2024": {
      id: "/archived/2022-01-08-post1-2024",
      path: "2022-01-08-post1-2024",
      fullPath: "/archived/2022-01-08-post1-2024",
      parentId: "/archived/index",
      children: [] as const,
      sourceFile: "/src/content/archived/2022-01-08-post1-2024.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/archived/2022-01-08-post1-2024"],
    "/archived/2022-01-10-post2-2024": {
      id: "/archived/2022-01-10-post2-2024",
      path: "2022-01-10-post2-2024",
      fullPath: "/archived/2022-01-10-post2-2024",
      parentId: "/archived/index",
      children: [] as const,
      sourceFile: "/src/content/archived/2022-01-10-post2-2024.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/archived/2022-01-10-post2-2024"],
    "/blog/index": {
      id: "/blog/index",
      path: "blog",
      fullPath: "/blog",
      parentId: null,
      children: ["/blog/[slug]", "/blog/posts/[slug]"] as const,
      sourceFile: "/src/app/pages/blog/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/blog/index"],
    "/contact": {
      id: "/contact",
      path: "contact",
      fullPath: "/contact",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/contact.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/contact"],
    "/shared-test": {
      id: "/shared-test",
      path: "shared-test",
      fullPath: "/shared-test",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/content/shared-test.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/shared-test"],
    "/test": {
      id: "/test",
      path: "test",
      fullPath: "/test",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/test.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/test"],
    "/archived/[slug]": {
      id: "/archived/[slug]",
      path: "[slug]",
      fullPath: "/archived/[slug]",
      parentId: "/archived/index",
      children: [] as const,
      sourceFile: "/src/app/pages/archived/[slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/archived/[slug]"],
    "/blog/[slug]": {
      id: "/blog/[slug]",
      path: "[slug]",
      fullPath: "/blog/[slug]",
      parentId: "/blog/index",
      children: [] as const,
      sourceFile: "/src/app/pages/blog/[slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/blog/[slug]"],
    "/blog/posts/[slug]": {
      id: "/blog/posts/[slug]",
      path: "posts/[slug]",
      fullPath: "/blog/posts/[slug]",
      parentId: "/blog/index",
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/blog/posts.[slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/blog/posts/[slug]"],
    "/[...page-not-found]": {
      id: "/[...page-not-found]",
      path: "[...page-not-found]",
      fullPath: "/[...page-not-found]",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/[...page-not-found].md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: true,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/[...page-not-found]"],
  },
  byFullPath: {
    "/": "/index",
    "/2022-12-27-my-first-post": "/2022-12-27-my-first-post",
    "/2022-12-31-my-second-post": "/2022-12-31-my-second-post",
    "/about": "/about",
    "/about-me": "/about-me",
    "/another-test": "/another-test",
    "/archived": "/archived/index",
    "/archived/2022-01-08-post1-2024": "/archived/2022-01-08-post1-2024",
    "/archived/2022-01-10-post2-2024": "/archived/2022-01-10-post2-2024",
    "/blog": "/blog/index",
    "/contact": "/contact",
    "/shared-test": "/shared-test",
    "/test": "/test",
    "/archived/[slug]": "/archived/[slug]",
    "/blog/[slug]": "/blog/[slug]",
    "/blog/posts/[slug]": "/blog/posts/[slug]",
    "/[...page-not-found]": "/[...page-not-found]",
  },
} as const;
