import type { Plugin } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

/**
 * Injects a boot module into every bundle that registers the discovered
 * analog:* maps with @analogjs/router and @analogjs/content through
 * their internal setters. `provideFileRouter` and `provideContent` fold
 * the maps in at DI time when the Vite globs are empty, so an app
 * config needs no analog:* imports — the same ergonomics as the Vite
 * path, delivered through per-graph module state instead of module
 * patching (the partially-compiled FESMs would bypass the Angular
 * linker).
 *
 * The setters are deliberately not a global: the Angular builder
 * bundles the server entry and main.server as separate graphs, each
 * with its own copies of the packages and the app. The boot module's
 * imports resolve within its own graph, so each graph registers its own
 * import thunks — a process-wide global would hand one graph's
 * component defs to the other graph's router (a cross-runtime NG0203
 * at outlet activation).
 *
 * The boot module is a real file (esbuild's `inject` resolves paths,
 * and its analog:* imports still go through the other plugins), and the
 * directory carries a package.json marking it side-effectful so the
 * registration survives tree shaking regardless of the consuming
 * workspace's own sideEffects settings.
 */
export function analogInitPlugin(options?: { workspaceRoot?: string }): Plugin {
  const workspaceRoot = (options?.workspaceRoot ?? process.cwd()).replace(
    /\\/g,
    '/',
  );
  const dir = `${workspaceRoot}/node_modules/@analogjs/esbuild-manifests`;

  return {
    name: 'analog-init',
    setup(build) {
      mkdirSync(dir, { recursive: true });
      writeFileSync(
        `${dir}/package.json`,
        JSON.stringify({ type: 'module', sideEffects: true }, null, 2) + '\n',
      );
      writeFileSync(
        `${dir}/boot.mjs`,
        `// Generated by @analogjs/platform. Registers the discovered maps\n` +
          `// for provideFileRouter/provideContent to fold in at DI time.\n` +
          `import routeFiles, { routeFilesMeta } from 'analog:route-files';\n` +
          `import pageEndpoints from 'analog:page-endpoints';\n` +
          `import { contentFilesList, contentFiles } from 'analog:content-files';\n` +
          `import { \\u0275setAnalogEsbuildMaps } from '@analogjs/router';\n` +
          `import { \\u0275setAnalogEsbuildContentMaps } from '@analogjs/content';\n` +
          `\n` +
          `\\u0275setAnalogEsbuildMaps({ routeFiles, routeFilesMeta, pageEndpoints });\n` +
          `\\u0275setAnalogEsbuildContentMaps({ contentFilesList, contentFiles });\n`,
      );

      build.initialOptions.inject = [
        ...(build.initialOptions.inject ?? []),
        `${dir}/boot.mjs`,
      ];
    },
  };
}
