packages:
  - 'apps/docs-app'
allowBuilds:
  '@compodoc/compodoc': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  core-js-pure: true
  cypress: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  unrs-resolver: true
