/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    {
      id: 'introduction',
      label: 'Introduction',
      type: 'doc',
    },
    {
      id: 'getting-started',
      label: 'Getting Started',
      type: 'doc',
    },
    {
      items: [
        {
          items: [
            {
              id: 'features/routing/overview',
              key: 'routing-overview',
              label: 'Overview',
              type: 'doc',
            },
            {
              id: 'features/routing/metadata',
              label: 'Route Metadata',
              type: 'doc',
            },
            {
              id: 'features/routing/content',
              label: 'Content Routes',
              type: 'doc',
            },
            {
              id: 'features/routing/middleware',
              label: 'Middleware',
              type: 'doc',
            },
            {
              id: 'features/routing/typed-routes',
              label: 'Typed Routes (Experimental)',
              type: 'doc',
            },
          ],
          label: 'Routing',
          type: 'category',
        },
        {
          items: [
            {
              id: 'features/api/overview',
              key: 'api-overview',
              label: 'Overview',
              type: 'doc',
            },
            {
              id: 'features/api/websockets',
              label: 'Websockets',
              type: 'doc',
            },
            {
              id: 'features/api/og-image-generation',
              label: 'OG Image Generation',
              type: 'doc',
            },
          ],
          label: 'API Routes',
          type: 'category',
        },
        {
          items: [
            {
              id: 'features/data-fetching/overview',
              key: 'data-fetching-overview',
              label: 'Overview',
              type: 'doc',
            },
            {
              id: 'features/data-fetching/server-side-data-fetching',
              label: 'Server-Side Data Fetching',
              type: 'doc',
            },
            {
              id: 'features/data-fetching/validation',
              label: 'Schema Validation',
              type: 'doc',
            },
          ],
          label: 'Data Fetching',
          type: 'category',
        },
        {
          items: [
            {
              id: 'features/server/static-site-generation',
              key: 'static-site-generation-overview',
              label: 'Overview',
              type: 'doc',
            },
          ],
          label: 'Static Site Generation',
          type: 'category',
        },
        {
          items: [
            {
              id: 'features/server/server-side-rendering',
              key: 'server-side-rendering-overview',
              label: 'Overview',
              type: 'doc',
            },
          ],
          label: 'Server Side Rendering',
          type: 'category',
        },
        {
          id: 'guides/forms',
          label: 'Form Actions',
          type: 'doc',
        },
        {
          items: [
            {
              id: 'features/generation/code-generation',
              key: 'code-generation-overview',
              label: 'Overview',
              type: 'doc',
            },
          ],
          label: 'Code Generation',
          type: 'category',
        },
      ],
      label: 'Core Concepts',
      type: 'category',
    },
    {
      items: [
        {
          id: 'features/deployment/overview',
          key: 'deployment-overview',
          label: 'Overview',
          type: 'doc',
        },
        {
          id: 'features/deployment/providers',
          label: 'Providers',
          type: 'doc',
        },
      ],
      label: 'Deployment',
      type: 'category',
    },
    {
      items: [
        {
          id: 'features/testing/overview',
          key: 'testing-overview',
          label: 'Overview',
          type: 'doc',
        },
        {
          id: 'features/testing/vitest',
          label: 'Setting Up Vitest',
          type: 'doc',
        },
      ],
      label: 'Testing w/Vitest',
      type: 'category',
    },
    {
      items: [
        {
          id: 'features/updating/overview',
          key: 'updating-overview',
          label: 'Overview',
          type: 'doc',
        },
      ],
      label: 'Updating',
      type: 'category',
    },
    {
      items: [
        {
          id: 'guides/migrating',
          label: 'Migrating an Angular app to Analog',
          type: 'doc',
        },
        {
          id: 'guides/migrating-v1-to-v2',
          label: 'Migrating from Analog v1 to v2',
          type: 'doc',
        },
        {
          id: 'guides/migrating-v2-to-v3',
          label: 'Migrating from Analog v2 to v3',
          type: 'doc',
        },
        {
          id: 'guides/libraries',
          label: 'Building an Angular library',
          type: 'doc',
        },
        {
          id: 'guides/compatibility',
          label: 'Version Compatibilty',
          type: 'doc',
        },
        {
          id: 'guides/idiomatic',
          label: 'Idiomatic Analog',
          type: 'doc',
        },
        {
          id: 'guides/debugging',
          label: 'Debugging',
          type: 'doc',
        },
      ],
      label: 'Guides',
      type: 'category',
    },
    {
      items: [
        {
          id: 'integrations/nx/index',
          label: 'Nx',
          type: 'doc',
        },
        {
          id: 'packages/astro-angular/overview',
          label: 'Astro',
          type: 'doc',
        },
        {
          id: 'packages/vite-plugin-angular/overview',
          label: 'Vite',
          type: 'doc',
        },
        {
          id: 'packages/vite-plugin-nitro/overview',
          label: 'Nitro',
          type: 'doc',
        },
        {
          id: 'integrations/angular-material/index',
          label: 'Angular Material',
          type: 'doc',
        },
        {
          id: 'integrations/ionic/index',
          label: 'Ionic Framework',
          type: 'doc',
        },
        {
          id: 'integrations/storybook/index',
          label: 'Storybook',
          type: 'doc',
        },
      ],
      label: 'Integrations',
      type: 'category',
    },
    {
      id: 'contributors',
      label: 'Contributors',
      type: 'doc',
    },
    {
      id: 'support',
      label: 'Support',
      type: 'doc',
    },
  ],

  // But you can create a sidebar manually
  /*
  DocsSidebar: [
    {
      type: 'category',
      label: 'Docs',
      items: ['introduction'],
    },
  ],
   */
};

module.exports = sidebars;
