/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        {
          type: 'category',
          label: 'Routing',
          items: [
            {
              type: 'doc',
              id: 'features/routing/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'features/routing/metadata',
              label: 'Route Metadata & SEO',
            },
            {
              type: 'doc',
              id: 'features/routing/content',
              label: 'Content Routes',
            },
            {
              type: 'doc',
              id: 'features/routing/middleware',
              label: 'Middleware',
            },
          ],
        },
        {
          type: 'category',
          label: 'API Routes',
          items: [
            {
              type: 'doc',
              id: 'features/api/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'features/api/websockets',
              label: 'Websockets',
            },
            {
              type: 'doc',
              id: 'features/api/og-image-generation',
              label: 'OG Image Generation',
            },
          ],
        },
        {
          type: 'category',
          label: 'Data Fetching',
          items: [
            {
              type: 'doc',
              id: 'features/data-fetching/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'features/data-fetching/server-side-data-fetching',
              label: 'Server-Side Data Fetching',
            },
          ],
        },
        {
          type: 'category',
          label: 'Rendering',
          items: [
            {
              type: 'doc',
              id: 'features/server/server-side-rendering',
              label: 'Server-Side Rendering (SSR)',
            },
            {
              type: 'doc',
              id: 'features/server/static-site-generation',
              label: 'Static Site Generation (SSG)',
            },
            // {
            //   type: 'doc',
            //   id: 'features/server/hybrid-rendering',
            //   label: 'Hybrid Rendering',
            // },
          ],
        },
        {
          type: 'category',
          label: 'Code Generation',
          items: [
            {
              type: 'doc',
              id: 'features/generation/code-generation',
              label: 'Overview',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {
          type: 'doc',
          id: 'features/deployment/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'features/deployment/providers',
          label: 'Providers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        {
          type: 'doc',
          id: 'features/testing/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'features/testing/vitest',
          label: 'Adding Vitest',
        },
      ],
    },
    {
      type: 'category',
      label: 'Updating',
      items: [
        {
          type: 'doc',
          id: 'features/updating/overview',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'doc',
          id: 'guides/migrating',
          label: 'Migrating an Angular app to Analog',
        },
        {
          type: 'doc',
          id: 'guides/libraries',
          label: 'Building an Angular library',
        },
        {
          type: 'doc',
          id: 'guides/compatibility',
          label: 'Version Compatibility',
        },
        {
          type: 'doc',
          id: 'guides/forms',
          label: 'Form Actions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        {
          type: 'category',
          label: 'Content',
          items: [
            {
              type: 'doc',
              id: 'packages/content/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'packages/content/shiki-highlighter',
              label: 'Shiki Highlighter',
            },
            {
              type: 'doc',
              id: 'packages/content/prism-highlighter',
              label: 'Prism Highlighter',
            },
          ],
        },
        {
          type: 'category',
          label: 'Router',
          items: [
            {
              type: 'doc',
              id: 'packages/router/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'packages/router/api-reference',
              label: 'API Reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            {
              type: 'doc',
              id: 'packages/vitest-angular/overview',
              label: 'Vitest Angular',
            },
          ],
        },
        {
          type: 'category',
          label: 'Platform',
          items: [
            {
              type: 'doc',
              id: 'packages/platform/overview',
              label: 'Overview',
            },
          ],
        },
        {
          type: 'doc',
          id: 'guides/forms',
          label: 'Form Actions',
        },
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [
        // {
        //   type: 'category',
        //   label: 'Content',
        //   items: [
        //     {
        //       type: 'doc',
        //       id: 'packages/content/overview',
        //       label: 'Overview',
        //     },
        //     {
        //       type: 'doc',
        //       id: 'packages/content/shiki-highlighter',
        //       label: 'Shiki Highlighter',
        //     },
        //     {
        //       type: 'doc',
        //       id: 'packages/content/prism-highlighter',
        //       label: 'Prism Highlighter',
        //     },
        //   ],
        // },
        {
          type: 'category',
          label: 'Router',
          items: [
            {
              type: 'doc',
              id: 'packages/router/overview',
              label: 'Overview',
            },
            // {
            //   type: 'doc',
            //   id: 'packages/router/api-reference',
            //   label: 'API Reference',
            // },
          ],
        },
        // {
        //   type: 'category',
        //   label: 'Testing',
        //   items: [
        //     {
        //       type: 'doc',
        //       id: 'packages/vitest-angular/overview',
        //       label: 'Vitest Angular',
        //     },
        //   ],
        // },
        // {
        //   type: 'category',
        //   label: 'Platform',
        //   items: [
        //     {
        //       type: 'doc',
        //       id: 'packages/platform/overview',
        //       label: 'Overview',
        //     },
        //   ],
        // },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'category',
          label: 'Build Tools',
          items: [
            {
              type: 'doc',
              id: 'integrations/nx/index',
              label: 'Nx',
            },
            {
              type: 'doc',
              id: 'packages/vite-plugin-angular/overview',
              label: 'Vite',
            },
            {
              type: 'doc',
              id: 'packages/vite-plugin-nitro/overview',
              label: 'Nitro',
            },
          ],
        },
        {
          type: 'category',
          label: 'UI Frameworks',
          items: [
            {
              type: 'doc',
              id: 'integrations/angular-material/index',
              label: 'Angular Material',
            },
            {
              type: 'doc',
              id: 'integrations/ionic/index',
              label: 'Ionic Framework',
            },
          ],
        },
        {
          type: 'category',
          label: 'Content & Development',
          items: [
            {
              type: 'doc',
              id: 'packages/astro-angular/overview',
              label: 'Astro',
            },
            {
              type: 'doc',
              id: 'integrations/storybook/index',
              label: 'Storybook',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Experimental',
      items: [
        {
          type: 'doc',
          id: 'experimental/sfc/index',
          label: 'Analog SFCs',
        },
      ],
    },
    {
      type: 'doc',
      id: 'contributors',
      label: 'Contributors',
    },
    {
      type: 'doc',
      id: 'support',
      label: 'Support',
    },
  ],

  // But you can create a sidebar manually
  /*
  docsSidebar: [
    {
      type: 'category',
      label: 'Docs',
      items: ['introduction'],
    },
  ],
   */
};

export default sidebars;
