/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by @analogjs/vite-plugin-angular
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Component } from '@angular/core'
import { Routes } from '@angular/router'
import type { Route } from '@angular/router'
import type { WithContext, Thing } from 'schema-dts'

import IndexComponent from './pages/(home).page'
import { routeMeta as IndexRouteMeta } from './pages/(home).page'
import CatchAllComponent from './pages/[...slug].page'
import ArticleComponent from './pages/article.page'
import { routeMeta as ArticleRouteMeta } from './pages/article.page'
import { routeJsonLd as ArticleJsonLd } from './pages/article.page'
import AuthComponent from './pages/(auth).page'
import CartComponent from './pages/cart.page'
import EventComponent from './pages/event.page'
import { routeJsonLd as EventJsonLd } from './pages/event.page'
import GoodbyeComponent from './pages/goodbye.page'
import NewsletterComponent from './pages/newsletter.page'
import PackageComponent from './pages/package.page'
import ProductComponent from './pages/product.page'
import { routeJsonLd as ProductJsonLd } from './pages/product.page'
import SearchComponent from './pages/search.page'
import TestMetaComponent from './pages/test-meta.page'
import { routeMeta as TestMetaRouteMeta } from './pages/test-meta.page'
import AuthSignUpComponent from './pages/(auth)/sign-up.page'
import ClientClientComponent from './pages/client/(client).page'
import ProductsProductIdComponent from './pages/products.[productId].page'
import ServerServerComponent from './pages/server/(server).page'
import { routeMeta as ServerServerRouteMeta } from './pages/server/(server).page'
import ShippingCatchAllComponent from './pages/shipping/[...slug].page'
import ShippingIndexComponent from './pages/shipping/index.page'

const IndexRoute = IndexComponent
const CatchAllRoute = CatchAllComponent
const ArticleRoute = ArticleComponent
const AuthRoute = AuthComponent
const CartRoute = CartComponent
const EventRoute = EventComponent
const GoodbyeRoute = GoodbyeComponent
const NewsletterRoute = NewsletterComponent
const PackageRoute = PackageComponent
const ProductRoute = ProductComponent
const SearchRoute = SearchComponent
const TestMetaRoute = TestMetaComponent
const AuthSignUpRoute = AuthSignUpComponent
const ClientClientRoute = ClientClientComponent
const ProductsProductIdRoute = ProductsProductIdComponent
const ServerServerRoute = ServerServerComponent
const ShippingCatchAllRoute = ShippingCatchAllComponent
const ShippingIndexRoute = ShippingIndexComponent


export interface FileRoutesByPath {
  '/': typeof IndexRoute,
  '/**': typeof CatchAllRoute,
  '/article': typeof ArticleRoute,
  '/auth': typeof AuthRoute,
  '/cart': typeof CartRoute,
  '/event': typeof EventRoute,
  '/goodbye': typeof GoodbyeRoute,
  '/newsletter': typeof NewsletterRoute,
  '/package': typeof PackageRoute,
  '/product': typeof ProductRoute,
  '/search': typeof SearchRoute,
  '/test-meta': typeof TestMetaRoute,
  '/(auth)/sign-up': typeof AuthSignUpRoute,
  '/client/(client)': typeof ClientClientRoute,
  '/products/:productId': typeof ProductsProductIdRoute,
  '/server/(server)': typeof ServerServerRoute,
  '/shipping/**': typeof ShippingCatchAllRoute,
  '/shipping/index': typeof ShippingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute,
  '/**': typeof CatchAllRoute,
  '/article': typeof ArticleRoute,
  '/auth': typeof AuthRoute,
  '/cart': typeof CartRoute,
  '/event': typeof EventRoute,
  '/goodbye': typeof GoodbyeRoute,
  '/newsletter': typeof NewsletterRoute,
  '/package': typeof PackageRoute,
  '/product': typeof ProductRoute,
  '/search': typeof SearchRoute,
  '/test-meta': typeof TestMetaRoute,
  '/(auth)/sign-up': typeof AuthSignUpRoute,
  '/client/(client)': typeof ClientClientRoute,
  '/products/:productId': typeof ProductsProductIdRoute,
  '/server/(server)': typeof ServerServerRoute,
  '/shipping/**': typeof ShippingCatchAllRoute,
  '/shipping/index': typeof ShippingIndexRoute
}

export interface FileRoutesById {
  '/': typeof IndexRoute,
  '/**': typeof CatchAllRoute,
  '/article': typeof ArticleRoute,
  '/auth': typeof AuthRoute,
  '/cart': typeof CartRoute,
  '/event': typeof EventRoute,
  '/goodbye': typeof GoodbyeRoute,
  '/newsletter': typeof NewsletterRoute,
  '/package': typeof PackageRoute,
  '/product': typeof ProductRoute,
  '/search': typeof SearchRoute,
  '/test-meta': typeof TestMetaRoute,
  '/(auth)/sign-up': typeof AuthSignUpRoute,
  '/client/(client)': typeof ClientClientRoute,
  '/products/:productId': typeof ProductsProductIdRoute,
  '/server/(server)': typeof ServerServerRoute,
  '/shipping/**': typeof ShippingCatchAllRoute,
  '/shipping/index': typeof ShippingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByPath: FileRoutesByPath
  fullPaths: '/' | '/**' | '/article' | '/auth' | '/cart' | '/event' | '/goodbye' | '/newsletter' | '/package' | '/product' | '/search' | '/test-meta' | '/(auth)/sign-up' | '/client/(client)' | '/products/:productId' | '/server/(server)' | '/shipping/**' | '/shipping/index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/**' | '/article' | '/auth' | '/cart' | '/event' | '/goodbye' | '/newsletter' | '/package' | '/product' | '/search' | '/test-meta' | '/(auth)/sign-up' | '/client/(client)' | '/products/:productId' | '/server/(server)' | '/shipping/**' | '/shipping/index'
  id: '/' | '/**' | '/article' | '/auth' | '/cart' | '/event' | '/goodbye' | '/newsletter' | '/package' | '/product' | '/search' | '/test-meta' | '/(auth)/sign-up' | '/client/(client)' | '/products/:productId' | '/server/(server)' | '/shipping/**' | '/shipping/index'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute,
  CatchAllRoute: typeof CatchAllRoute,
  ArticleRoute: typeof ArticleRoute,
  AuthRoute: typeof AuthRoute,
  CartRoute: typeof CartRoute,
  EventRoute: typeof EventRoute,
  GoodbyeRoute: typeof GoodbyeRoute,
  NewsletterRoute: typeof NewsletterRoute,
  PackageRoute: typeof PackageRoute,
  ProductRoute: typeof ProductRoute,
  SearchRoute: typeof SearchRoute,
  TestMetaRoute: typeof TestMetaRoute,
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatchAllRoute: CatchAllRoute,
  ArticleRoute: ArticleRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  EventRoute: EventRoute,
  GoodbyeRoute: GoodbyeRoute,
  NewsletterRoute: NewsletterRoute,
  PackageRoute: PackageRoute,
  ProductRoute: ProductRoute,
  SearchRoute: SearchRoute,
  TestMetaRoute: TestMetaRoute,
  ProductsProductIdRoute: ProductsProductIdRoute
}

export const routeTree = rootRouteChildren

// Map of routes to their JSON-LD data
export const routeJsonLdMap = new Map<string, any>([
  ['/article', ArticleJsonLd],
  ['/event', EventJsonLd],
  ['/product', ProductJsonLd]
])

// Type for Angular Route metadata (excludes file-based properties)
export type RouteMeta = Omit<Route, 'component' | 'loadComponent' | 'loadChildren' | 'path' | 'pathMatch'>

// Type for JSON-LD structured data
export type JsonLd = WithContext<Thing>

declare module '@analogjs/router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      component: typeof IndexComponent
      routeMeta: typeof IndexRouteMeta
      parentRoute: typeof rootRoute
    }
    '/**': {
      id: '/**'
      path: '/**'
      fullPath: '/**'
      component: typeof CatchAllComponent
      parentRoute: typeof rootRoute
    }
    '/article': {
      id: '/article'
      path: '/article'
      fullPath: '/article'
      component: typeof ArticleComponent
      routeMeta: typeof ArticleRouteMeta
      jsonLd: typeof ArticleJsonLd
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      component: typeof AuthComponent
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      component: typeof CartComponent
      parentRoute: typeof rootRoute
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      component: typeof EventComponent
      jsonLd: typeof EventJsonLd
      parentRoute: typeof rootRoute
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      component: typeof GoodbyeComponent
      parentRoute: typeof rootRoute
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      component: typeof NewsletterComponent
      parentRoute: typeof rootRoute
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      component: typeof PackageComponent
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      component: typeof ProductComponent
      jsonLd: typeof ProductJsonLd
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      component: typeof SearchComponent
      parentRoute: typeof rootRoute
    }
    '/test-meta': {
      id: '/test-meta'
      path: '/test-meta'
      fullPath: '/test-meta'
      component: typeof TestMetaComponent
      routeMeta: typeof TestMetaRouteMeta
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/(auth)/sign-up'
      fullPath: '/(auth)/sign-up'
      component: typeof AuthSignUpComponent
      parentRoute: typeof rootRoute
    }
    '/client/(client)': {
      id: '/client/(client)'
      path: '/client/(client)'
      fullPath: '/client/(client)'
      component: typeof ClientClientComponent
      parentRoute: typeof rootRoute
    }
    '/products/:productId': {
      id: '/products/:productId'
      path: '/products/:productId'
      fullPath: '/products/:productId'
      component: typeof ProductsProductIdComponent
      parentRoute: typeof rootRoute
    }
    '/server/(server)': {
      id: '/server/(server)'
      path: '/server/(server)'
      fullPath: '/server/(server)'
      component: typeof ServerServerComponent
      routeMeta: typeof ServerServerRouteMeta
      parentRoute: typeof rootRoute
    }
    '/shipping/**': {
      id: '/shipping/**'
      path: '/shipping/**'
      fullPath: '/shipping/**'
      component: typeof ShippingCatchAllComponent
      parentRoute: typeof rootRoute
    }
    '/shipping/index': {
      id: '/shipping/index'
      path: '/shipping/index'
      fullPath: '/shipping/index'
      component: typeof ShippingIndexComponent
      parentRoute: typeof rootRoute
    }
  }
}

// Utility types for type-safe navigation
export type AnalogRoute = keyof FileRoutesByPath

// Extract route params from path
export type ExtractParams<T extends string> =
  T extends `${string}/:${infer Param}/${infer Rest}`
    ? { [K in Param]: string } & ExtractParams<`/${Rest}`>
    : T extends `${string}/:${infer Param}`
    ? { [K in Param]: string }
    : {}

export type RouteParams<T extends AnalogRoute> = ExtractParams<T>
