/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/about-me': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/cart': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/newsletter': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/newsletter.server').load;
    };
    '/package': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/search': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/search.server').load;
    };
    '/server-functions': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/shipping': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/shipping/index.server').load;
    };
    '/sign-up': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/test': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      load: typeof import('../../../libs/shared/feature/src/pages/test.server').load;
    };
    '/blog/[slug]': {
      params: { slug: string };
      query: Record<string, string | string[] | undefined>;
    };
    '/products/[productId]': {
      params: { productId: string };
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/products.[productId].server').load;
    };
    '/[...slug]': {
      params: { slug: string[] };
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/[...slug].server').load;
    };
    '/shipping/[...slug]': {
      params: { slug: string[] };
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/shipping/[...slug].server').load;
    };
  }
}

export {};
