// This file is auto-generated by @analogjs/vite-plugin-routes
// Do not edit manually

import type { Graph, Thing, WithContext } from 'schema-dts';
import * as routeModule0 from './app/pages/(home).page';
import * as routeModule1 from './app/pages/client/(client).page';
import * as routeModule2 from './app/pages/products.[productId].page';

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/about-me': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/cart': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/client': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/newsletter': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/package': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/search': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/server': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/shipping': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/sign-up': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/test': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/blog/[slug]': {
      params: { slug: string };
      paramsOutput: { slug: string };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/products/[productId]': {
      params: { productId: string };
      paramsOutput: { productId: string };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/[...slug]': {
      params: { slug: string[] };
      paramsOutput: { slug: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/shipping/[...slug]': {
      params: { slug: string[] };
      paramsOutput: { slug: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/(auth)": AnalogGeneratedRouteRecord<"/(auth)", "/", "/", null, readonly []>;
  "/about-me": AnalogGeneratedRouteRecord<"/about-me", "about-me", "/about-me", null, readonly []>;
  "/cart": AnalogGeneratedRouteRecord<"/cart", "cart", "/cart", null, readonly []>;
  "/client/(client)": AnalogGeneratedRouteRecord<"/client/(client)", "client", "/client", null, readonly []>;
  "/newsletter": AnalogGeneratedRouteRecord<"/newsletter", "newsletter", "/newsletter", null, readonly []>;
  "/package": AnalogGeneratedRouteRecord<"/package", "package", "/package", null, readonly []>;
  "/search": AnalogGeneratedRouteRecord<"/search", "search", "/search", null, readonly []>;
  "/server/(server)": AnalogGeneratedRouteRecord<"/server/(server)", "server", "/server", null, readonly []>;
  "/shipping/index": AnalogGeneratedRouteRecord<"/shipping/index", "shipping", "/shipping", null, readonly ["/shipping/[...slug]"]>;
  "/(auth)/sign-up": AnalogGeneratedRouteRecord<"/(auth)/sign-up", "sign-up", "/sign-up", null, readonly []>;
  "/test": AnalogGeneratedRouteRecord<"/test", "test", "/test", null, readonly []>;
  "/blog/[slug]": AnalogGeneratedRouteRecord<"/blog/[slug]", "blog/[slug]", "/blog/[slug]", null, readonly []>;
  "/products/[productId]": AnalogGeneratedRouteRecord<"/products/[productId]", "products/[productId]", "/products/[productId]", null, readonly []>;
  "/[...slug]": AnalogGeneratedRouteRecord<"/[...slug]", "[...slug]", "/[...slug]", null, readonly []>;
  "/shipping/[...slug]": AnalogGeneratedRouteRecord<"/shipping/[...slug]", "[...slug]", "/shipping/[...slug]", "/shipping/index", readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/(auth)"];
  "/about-me": AnalogFileRoutesById["/about-me"];
  "/cart": AnalogFileRoutesById["/cart"];
  "/client": AnalogFileRoutesById["/client/(client)"];
  "/newsletter": AnalogFileRoutesById["/newsletter"];
  "/package": AnalogFileRoutesById["/package"];
  "/search": AnalogFileRoutesById["/search"];
  "/server": AnalogFileRoutesById["/server/(server)"];
  "/shipping": AnalogFileRoutesById["/shipping/index"];
  "/sign-up": AnalogFileRoutesById["/(auth)/sign-up"];
  "/test": AnalogFileRoutesById["/test"];
  "/blog/[slug]": AnalogFileRoutesById["/blog/[slug]"];
  "/products/[productId]": AnalogFileRoutesById["/products/[productId]"];
  "/[...slug]": AnalogFileRoutesById["/[...slug]"];
  "/shipping/[...slug]": AnalogFileRoutesById["/shipping/[...slug]"];
}

export interface AnalogFileRoutesByTo {
  "/": AnalogFileRoutesById["/(auth)"];
  "/about-me": AnalogFileRoutesById["/about-me"];
  "/cart": AnalogFileRoutesById["/cart"];
  "/client": AnalogFileRoutesById["/client/(client)"];
  "/newsletter": AnalogFileRoutesById["/newsletter"];
  "/package": AnalogFileRoutesById["/package"];
  "/search": AnalogFileRoutesById["/search"];
  "/server": AnalogFileRoutesById["/server/(server)"];
  "/shipping": AnalogFileRoutesById["/shipping/index"];
  "/sign-up": AnalogFileRoutesById["/(auth)/sign-up"];
  "/test": AnalogFileRoutesById["/test"];
  "/blog/[slug]": AnalogFileRoutesById["/blog/[slug]"];
  "/products/[productId]": AnalogFileRoutesById["/products/[productId]"];
  "/[...slug]": AnalogFileRoutesById["/[...slug]"];
  "/shipping/[...slug]": AnalogFileRoutesById["/shipping/[...slug]"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;
export type AnalogRouteTreeTo = keyof AnalogFileRoutesByTo;

export const analogRouteTree = {
  byId: {
    "/(auth)": {
      id: "/(auth)",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/(auth).page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/(auth)"],
    "/about-me": {
      id: "/about-me",
      path: "about-me",
      fullPath: "/about-me",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/about-me.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/about-me"],
    "/cart": {
      id: "/cart",
      path: "cart",
      fullPath: "/cart",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/cart.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/cart"],
    "/client/(client)": {
      id: "/client/(client)",
      path: "client",
      fullPath: "/client",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/client/(client).page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/client/(client)"],
    "/newsletter": {
      id: "/newsletter",
      path: "newsletter",
      fullPath: "/newsletter",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/newsletter.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/newsletter"],
    "/package": {
      id: "/package",
      path: "package",
      fullPath: "/package",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/package.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/package"],
    "/search": {
      id: "/search",
      path: "search",
      fullPath: "/search",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/search.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/search"],
    "/server/(server)": {
      id: "/server/(server)",
      path: "server",
      fullPath: "/server",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/server/(server).page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/server/(server)"],
    "/shipping/index": {
      id: "/shipping/index",
      path: "shipping",
      fullPath: "/shipping",
      parentId: null,
      children: ["/shipping/[...slug]"] as const,
      sourceFile: "/src/app/pages/shipping/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/shipping/index"],
    "/(auth)/sign-up": {
      id: "/(auth)/sign-up",
      path: "sign-up",
      fullPath: "/sign-up",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/(auth)/sign-up.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/(auth)/sign-up"],
    "/test": {
      id: "/test",
      path: "test",
      fullPath: "/test",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/test.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/test"],
    "/blog/[slug]": {
      id: "/blog/[slug]",
      path: "blog/[slug]",
      fullPath: "/blog/[slug]",
      parentId: null,
      children: [] as const,
      sourceFile: "/libs/shared/feature/src/pages/blog/[slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/blog/[slug]"],
    "/products/[productId]": {
      id: "/products/[productId]",
      path: "products/[productId]",
      fullPath: "/products/[productId]",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/products.[productId].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/products/[productId]"],
    "/[...slug]": {
      id: "/[...slug]",
      path: "[...slug]",
      fullPath: "/[...slug]",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/[...slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: true,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/[...slug]"],
    "/shipping/[...slug]": {
      id: "/shipping/[...slug]",
      path: "[...slug]",
      fullPath: "/shipping/[...slug]",
      parentId: "/shipping/index",
      children: [] as const,
      sourceFile: "/src/app/pages/shipping/[...slug].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: true,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/shipping/[...slug]"],
  },
  byFullPath: {
    "/": "/(auth)",
    "/about-me": "/about-me",
    "/cart": "/cart",
    "/client": "/client/(client)",
    "/newsletter": "/newsletter",
    "/package": "/package",
    "/search": "/search",
    "/server": "/server/(server)",
    "/shipping": "/shipping/index",
    "/sign-up": "/(auth)/sign-up",
    "/test": "/test",
    "/blog/[slug]": "/blog/[slug]",
    "/products/[productId]": "/products/[productId]",
    "/[...slug]": "/[...slug]",
    "/shipping/[...slug]": "/shipping/[...slug]",
  },
  byTo: {
    "/": "/(auth)",
    "/about-me": "/about-me",
    "/cart": "/cart",
    "/client": "/client/(client)",
    "/newsletter": "/newsletter",
    "/package": "/package",
    "/search": "/search",
    "/server": "/server/(server)",
    "/shipping": "/shipping/index",
    "/sign-up": "/(auth)/sign-up",
    "/test": "/test",
    "/blog/[slug]": "/blog/[slug]",
    "/products/[productId]": "/products/[productId]",
    "/[...slug]": "/[...slug]",
    "/shipping/[...slug]": "/shipping/[...slug]",
  },
} as const;

export type AnalogJsonLdDocument = WithContext<Thing> | Graph | Array<WithContext<Thing>>;
export type GeneratedJsonLdManifestEntry = { routePath: string; sourceFile: string; kind: 'module' | 'content'; resolveJsonLd: () => AnalogJsonLdDocument[]; };

function normalizeJsonLd(value: unknown): AnalogJsonLdDocument[] {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is AnalogJsonLdDocument => typeof entry === 'object' && entry !== null && !Array.isArray(entry));
  }

  return typeof value === 'object' && value !== null ? [value as AnalogJsonLdDocument] : [];
}

function resolveModuleJsonLd(routeModule: unknown): AnalogJsonLdDocument[] {
  const typedRouteModule = routeModule as { routeJsonLd?: unknown; routeMeta?: { jsonLd?: unknown } };
  return normalizeJsonLd(typedRouteModule.routeMeta?.jsonLd ?? typedRouteModule.routeJsonLd);
}

export const routeJsonLdManifest = new Map<string, GeneratedJsonLdManifestEntry>([
  ['/', { routePath: '/', sourceFile: '/src/app/pages/(home).page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule0) }],
  ['/client', { routePath: '/client', sourceFile: '/src/app/pages/client/(client).page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule1) }],
  ['/products/[productId]', { routePath: '/products/[productId]', sourceFile: '/src/app/pages/products.[productId].page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule2) }],
]);
