// This file is auto-generated by @analogjs/platform
// Do not edit manually

import type { Graph, Thing, WithContext } from 'schema-dts';
import * as routeModule0 from './app/pages/(home).page';

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/probe': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/(home)": AnalogGeneratedRouteRecord<"/(home)", "/", "/", null, readonly []>;
  "/probe": AnalogGeneratedRouteRecord<"/probe", "probe", "/probe", null, readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/(home)"];
  "/probe": AnalogFileRoutesById["/probe"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/(home)": {
      id: "/(home)",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/(home).page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: true,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/(home)"],
    "/probe": {
      id: "/probe",
      path: "probe",
      fullPath: "/probe",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/probe.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/probe"],
  },
  byFullPath: {
    "/": "/(home)",
    "/probe": "/probe",
  },
} as const;

export type AnalogJsonLdDocument = WithContext<Thing> | Graph | Array<WithContext<Thing>>;
export type GeneratedJsonLdManifestEntry = { routePath: string; sourceFile: string; kind: 'module' | 'content'; resolveJsonLd: () => AnalogJsonLdDocument[]; };

function normalizeJsonLd(value: unknown): AnalogJsonLdDocument[] {
  if (Array.isArray(value)) {
    return value.filter((entry): entry is AnalogJsonLdDocument => typeof entry === 'object' && entry !== null && !Array.isArray(entry));
  }

  return typeof value === 'object' && value !== null ? [value as AnalogJsonLdDocument] : [];
}

function resolveModuleJsonLd(routeModule: unknown): AnalogJsonLdDocument[] {
  const typedRouteModule = routeModule as { routeJsonLd?: unknown; routeMeta?: { jsonLd?: unknown } };
  return normalizeJsonLd(typedRouteModule.routeMeta?.jsonLd ?? typedRouteModule.routeJsonLd);
}

export const routeJsonLdManifest = new Map<string, GeneratedJsonLdManifestEntry>([
  ['/', { routePath: '/', sourceFile: '/src/app/pages/(home).page.ts', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(routeModule0) }],
]);
