/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/(home).page').routeMeta;
    };
    '/probe': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
