// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
