/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/contributing': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/contributors': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/contributing': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/api/og-image-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/api/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/api/websockets': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/data-fetching/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/data-fetching/server-side-data-fetching': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/deployment/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/deployment/providers': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/generation/code-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/routing/content': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/routing/metadata': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/routing/middleware': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/routing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/server/server-side-rendering': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/server/static-site-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/testing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/testing/vitest': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/features/updating/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/getting-started': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/guides/compatibility': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/guides/migrating': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/integrations/ai': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/integrations/angular-material': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/integrations/ionic': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/integrations/nx': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/integrations/storybook': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/introduction': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/packages/astro-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/packages/create-analog/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/packages/router/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/packages/vite-plugin-angular/css-preprocessors': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/packages/vite-plugin-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/de/support': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/contributing': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/api/og-image-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/api/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/api/websockets': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/data-fetching/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/data-fetching/server-side-data-fetching': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/deployment/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/deployment/providers': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/generation/code-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/routing/content': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/routing/metadata': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/routing/middleware': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/routing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/server/server-side-rendering': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/server/static-site-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/testing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/testing/vitest': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/features/updating/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/getting-started': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/guides/compatibility': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/guides/forms': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/guides/libraries': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/guides/migrating': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/integrations/ai': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/integrations/angular-material': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/integrations/ionic': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/integrations/nx': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/integrations/storybook': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/introduction': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/packages/astro-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/packages/create-analog/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/packages/router/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/packages/vite-plugin-angular/css-preprocessors': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/packages/vite-plugin-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/es/support': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/api/og-image-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/api/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/api/websockets': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/data-fetching/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/data-fetching/server-functions': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/data-fetching/server-side-data-fetching': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/deployment/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/deployment/providers': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/generation/code-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/i18n/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/routing/content': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/routing/metadata': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/routing/middleware': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/routing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/routing/typed-routes': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/server/server-side-rendering': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/server/static-site-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/server/streaming-ssr': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/testing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/testing/vitest': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/features/updating/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/getting-started': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/guides/angular-compilation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/guides/compatibility': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/guides/forms': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/guides/libraries': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/guides/migrating': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/ai': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/angular-material': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/ionic': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/nx': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/storybook': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/integrations/tanstack-query': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/introduction': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/astro-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/create-analog/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/router/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/vite-plugin-angular/css-preprocessors': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/vite-plugin-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/packages/vite-plugin-nitro/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/pt-br/guides/forms': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/pt-br/introduction': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/sponsoring': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/support': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/api/og-image-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/api/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/api/websockets': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/data-fetching/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/data-fetching/server-side-data-fetching': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/deployment/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/deployment/providers': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/generation/code-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/routing/content': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/routing/metadata': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/routing/middleware': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/routing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/server/server-side-rendering': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/server/static-site-generation': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/testing/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/testing/vitest': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/features/updating/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/getting-started': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/guides/compatibility': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/guides/forms': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/guides/libraries': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/guides/migrating': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/integrations/ai': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/integrations/angular-material': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/integrations/ionic': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/integrations/nx': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/integrations/storybook': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/introduction': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/packages/astro-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/packages/create-analog/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/packages/vite-plugin-angular/css-preprocessors': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/packages/vite-plugin-angular/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/packages/vite-plugin-nitro/overview': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/zh-hans/support': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/[locale]/docs': {
      params: { locale: string };
      query: Record<string, string | string[] | undefined>;
    };
    '/[locale]/docs/[[...slug]]': {
      params: { slug?: string[]; locale: string };
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
