// This file is auto-generated by @analogjs/vite-plugin-routes
// Do not edit manually

import * as routeModule0 from '../src/app/pages/(home).page';
import * as routeModule1 from '../src/app/pages/client/(client).page';
import * as routeModule2 from '../src/app/pages/products.[productId].page';

type JsonLdObject = Record<string, unknown>;
type GeneratedJsonLdManifestEntry = {
  routePath: string;
  sourceFile: string;
  kind: 'module' | 'content';
  resolveJsonLd: () => JsonLdObject[];
};

function normalizeJsonLd(value: unknown): JsonLdObject[] {
  if (Array.isArray(value)) {
    return value.filter(
      (entry): entry is JsonLdObject =>
        typeof entry === 'object' && entry !== null && !Array.isArray(entry),
    );
  }

  return typeof value === 'object' && value !== null
    ? [value as JsonLdObject]
    : [];
}

export const routeJsonLdManifest = new Map<
  string,
  GeneratedJsonLdManifestEntry
>([
  [
    '/',
    {
      routePath: '/',
      sourceFile: '/src/app/pages/(home).page.ts',
      kind: 'module',
      resolveJsonLd: () =>
        normalizeJsonLd(
          routeModule0.routeJsonLd ?? routeModule0.routeMeta?.jsonLd,
        ),
    },
  ],
  [
    '/client',
    {
      routePath: '/client',
      sourceFile: '/src/app/pages/client/(client).page.ts',
      kind: 'module',
      resolveJsonLd: () =>
        normalizeJsonLd(
          routeModule1.routeJsonLd ?? routeModule1.routeMeta?.jsonLd,
        ),
    },
  ],
  [
    '/products/[productId]',
    {
      routePath: '/products/[productId]',
      sourceFile: '/src/app/pages/products.[productId].page.ts',
      kind: 'module',
      resolveJsonLd: () =>
        normalizeJsonLd(
          routeModule2.routeJsonLd ?? routeModule2.routeMeta?.jsonLd,
        ),
    },
  ],
]);
