import fm from 'front-matter';
import { normalizePath } from 'vite';
import { dirname, relative } from 'node:path';

import { normalizeJsonLd, type JsonLdObject } from './route-manifest.js';

export type JsonLdModuleManifestEntry = {
  kind: 'module';
  routePath: string;
  sourceFile: string;
  importAlias: string;
};

export type JsonLdContentManifestEntry = {
  kind: 'content';
  routePath: string;
  sourceFile: string;
  jsonLd: JsonLdObject[];
};

export type JsonLdManifestEntry =
  | JsonLdModuleManifestEntry
  | JsonLdContentManifestEntry;

/**
 * Heuristic detector for JSON-LD exports in route modules.
 *
 * This is intentionally regex-based for speed during file scanning.
 * It reliably detects these direct export patterns:
 *
 * - `export const routeJsonLd = ...`
 * - `export const routeMeta = { ..., jsonLd: ... }`
 * - `export const routeJsonLd = (route) => ...` (function form)
 *
 * Known limitations (not detected):
 *
 * - re-exports: `export { routeJsonLd } from './data'`
 * - aliased exports: `export { something as routeJsonLd }`
 * - default exports: `export default { jsonLd: ... }`
 * - indirect assignment: `const data = { jsonLd: ... }; export const routeMeta = data`
 *
 * Known false-positive risks:
 *
 * - comment text containing `export const routeJsonLd`
 * - unrelated `jsonLd` text appearing after `export const routeMeta`
 *
 * Prefer the supported direct export patterns listed above.
 */
export function detectJsonLdModuleExports(fileContent: string): boolean {
  return (
    /export\s+const\s+routeJsonLd\b/.test(fileContent) ||
    /export\s+const\s+routeMeta\b[\s\S]*?\bjsonLd\b/.test(fileContent)
  );
}

export function extractMarkdownJsonLd(rawContent: string): JsonLdObject[] {
  const { attributes } = fm<Record<string, unknown>>(rawContent);
  return normalizeJsonLd(attributes['jsonLd']);
}

export function generateJsonLdManifestSource(
  entries: JsonLdManifestEntry[],
  outFile: string,
): string {
  const lines: string[] = [];
  const moduleEntries = entries.filter(
    (entry): entry is JsonLdModuleManifestEntry => entry.kind === 'module',
  );

  lines.push('// This file is auto-generated by @analogjs/platform');
  lines.push('// Do not edit manually');
  lines.push('');

  lines.push("import type { Graph, Thing, WithContext } from 'schema-dts';");

  moduleEntries.forEach((entry) => {
    lines.push(
      `import * as ${entry.importAlias} from '${toImportPath(outFile, entry.sourceFile)}';`,
    );
  });

  lines.push('');
  lines.push(
    'export type AnalogJsonLdDocument = WithContext<Thing> | Graph | Array<WithContext<Thing>>;',
  );
  lines.push(
    "export type GeneratedJsonLdManifestEntry = { routePath: string; sourceFile: string; kind: 'module' | 'content'; resolveJsonLd: () => AnalogJsonLdDocument[]; };",
  );
  lines.push('');
  lines.push(
    'function normalizeJsonLd(value: unknown): AnalogJsonLdDocument[] {',
  );
  lines.push('  if (Array.isArray(value)) {');
  lines.push(
    "    return value.filter((entry): entry is AnalogJsonLdDocument => typeof entry === 'object' && entry !== null && !Array.isArray(entry));",
  );
  lines.push('  }');
  lines.push('');
  lines.push(
    "  return typeof value === 'object' && value !== null ? [value as AnalogJsonLdDocument] : [];",
  );
  lines.push('}');
  lines.push('');
  lines.push(
    'function resolveModuleJsonLd(routeModule: unknown): AnalogJsonLdDocument[] {',
  );
  lines.push(
    '  const typedRouteModule = routeModule as { routeJsonLd?: unknown; routeMeta?: { jsonLd?: unknown } };',
  );
  lines.push(
    // Match runtime precedence (mergeRouteJsonLdIntoRouteMeta in routes.ts):
    // routeMeta.jsonLd wins over standalone routeJsonLd.
    '  return normalizeJsonLd(typedRouteModule.routeMeta?.jsonLd ?? typedRouteModule.routeJsonLd);',
  );
  lines.push('}');
  lines.push('');
  lines.push(
    'export const routeJsonLdManifest = new Map<string, GeneratedJsonLdManifestEntry>([',
  );

  entries.forEach((entry) => {
    if (entry.kind === 'module') {
      lines.push(
        `  ['${entry.routePath}', { routePath: '${entry.routePath}', sourceFile: '${entry.sourceFile}', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(${entry.importAlias}) }],`,
      );
      return;
    }

    lines.push(
      `  ['${entry.routePath}', { routePath: '${entry.routePath}', sourceFile: '${entry.sourceFile}', kind: 'content', resolveJsonLd: () => ${JSON.stringify(entry.jsonLd)} }],`,
    );
  });

  lines.push(']);');
  lines.push('');

  return lines.join('\n');
}

function toImportPath(outFile: string, sourceFile: string): string {
  // JSON-LD entries are emitted inside the same generated route module, so
  // imports are always resolved relative to that single output file.
  const fromDir = dirname(outFile);
  const sourceNoExt = sourceFile
    .replace(/^\//, '')
    .replace(/\.(ts|js|analog|ag)$/, '');
  const relativePath = normalizePath(relative(fromDir, sourceNoExt));

  if (relativePath.startsWith('.')) {
    return relativePath;
  }

  return `./${relativePath}`;
}
