import fm from 'front-matter';
import { normalizePath, type Plugin } from 'vite';
import { globSync } from 'tinyglobby';
import { resolve, join, dirname, relative } from 'node:path';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'node:fs';

import {
  filenameToRoutePath,
  normalizeJsonLd,
  type JsonLdObject,
} from '@analogjs/router/manifest';

const DEFAULT_JSON_LD_MANIFEST_OUT_FILE = '.analog/route-jsonld.gen.ts';

export interface JsonLdManifestPluginOptions {
  /**
   * Output path for the generated JSON-LD manifest file, relative to the app root.
   *
   * @default '.analog/route-jsonld.gen.ts'
   */
  outFile?: string;
  /**
   * Workspace root used to resolve additional route/content directories.
   *
   * @default process.cwd()
   */
  workspaceRoot?: string;
  /**
   * Additional page directories to scan for `.page.ts` files.
   */
  additionalPagesDirs?: string[];
  /**
   * Additional content directories to scan for `.md` files.
   */
  additionalContentDirs?: string[];
}

export type JsonLdModuleManifestEntry = {
  kind: 'module';
  routePath: string;
  sourceFile: string;
  importAlias: string;
};

export type JsonLdContentManifestEntry = {
  kind: 'content';
  routePath: string;
  sourceFile: string;
  jsonLd: JsonLdObject[];
};

export type JsonLdManifestEntry =
  | JsonLdModuleManifestEntry
  | JsonLdContentManifestEntry;

export function detectJsonLdModuleExports(fileContent: string): boolean {
  return (
    /export\s+const\s+routeJsonLd\b/.test(fileContent) ||
    /export\s+const\s+routeMeta\b[\s\S]*?\bjsonLd\b/.test(fileContent)
  );
}

export function extractMarkdownJsonLd(rawContent: string): JsonLdObject[] {
  const { attributes } = fm<Record<string, unknown>>(rawContent);
  return normalizeJsonLd(attributes['jsonLd']);
}

export function generateJsonLdManifestSource(
  entries: JsonLdManifestEntry[],
  outFile: string,
): string {
  const lines: string[] = [];
  const moduleEntries = entries.filter(
    (entry): entry is JsonLdModuleManifestEntry => entry.kind === 'module',
  );

  lines.push('// This file is auto-generated by @analogjs/vite-plugin-routes');
  lines.push('// Do not edit manually');
  lines.push('');

  lines.push("import type { Graph, Thing, WithContext } from 'schema-dts';");

  moduleEntries.forEach((entry) => {
    lines.push(
      `import * as ${entry.importAlias} from '${toImportPath(outFile, entry.sourceFile)}';`,
    );
  });

  lines.push('');
  lines.push(
    'export type AnalogJsonLdDocument = WithContext<Thing> | Graph | Array<WithContext<Thing>>;',
  );
  lines.push(
    "export type GeneratedJsonLdManifestEntry = { routePath: string; sourceFile: string; kind: 'module' | 'content'; resolveJsonLd: () => AnalogJsonLdDocument[]; };",
  );
  lines.push('');
  lines.push(
    'function normalizeJsonLd(value: unknown): AnalogJsonLdDocument[] {',
  );
  lines.push('  if (Array.isArray(value)) {');
  lines.push(
    "    return value.filter((entry): entry is AnalogJsonLdDocument => typeof entry === 'object' && entry !== null && !Array.isArray(entry));",
  );
  lines.push('  }');
  lines.push('');
  lines.push(
    "  return typeof value === 'object' && value !== null ? [value as AnalogJsonLdDocument] : [];",
  );
  lines.push('}');
  lines.push('');
  lines.push(
    'function resolveModuleJsonLd(routeModule: unknown): AnalogJsonLdDocument[] {',
  );
  lines.push(
    '  const typedRouteModule = routeModule as { routeJsonLd?: unknown; routeMeta?: { jsonLd?: unknown } };',
  );
  lines.push(
    // Match runtime precedence (mergeRouteJsonLdIntoRouteMeta in routes.ts):
    // routeMeta.jsonLd wins over standalone routeJsonLd.
    '  return normalizeJsonLd(typedRouteModule.routeMeta?.jsonLd ?? typedRouteModule.routeJsonLd);',
  );
  lines.push('}');
  lines.push('');
  lines.push(
    'export const routeJsonLdManifest = new Map<string, GeneratedJsonLdManifestEntry>([',
  );

  entries.forEach((entry) => {
    if (entry.kind === 'module') {
      lines.push(
        `  ['${entry.routePath}', { routePath: '${entry.routePath}', sourceFile: '${entry.sourceFile}', kind: 'module', resolveJsonLd: () => resolveModuleJsonLd(${entry.importAlias}) }],`,
      );
      return;
    }

    lines.push(
      `  ['${entry.routePath}', { routePath: '${entry.routePath}', sourceFile: '${entry.sourceFile}', kind: 'content', resolveJsonLd: () => ${JSON.stringify(entry.jsonLd)} }],`,
    );
  });

  lines.push(']);');
  lines.push('');

  return lines.join('\n');
}

function resolvePluginOptions(
  options: JsonLdManifestPluginOptions = {},
): Required<JsonLdManifestPluginOptions> {
  return {
    outFile: options.outFile ?? DEFAULT_JSON_LD_MANIFEST_OUT_FILE,
    workspaceRoot: options.workspaceRoot ?? process.cwd(),
    additionalPagesDirs: options.additionalPagesDirs ?? [],
    additionalContentDirs: options.additionalContentDirs ?? [],
  };
}

export function jsonLdManifest(
  options: JsonLdManifestPluginOptions = {},
): Plugin {
  const resolvedOptions = resolvePluginOptions(options);
  const workspaceRoot = normalizePath(resolvedOptions.workspaceRoot);
  let root = '';

  function discoverRouteFiles(): string[] {
    return globSync(
      [
        `${root}/app/routes/**/*.ts`,
        `${root}/src/app/routes/**/*.ts`,
        `${root}/src/app/pages/**/*.page.ts`,
        ...resolvedOptions.additionalPagesDirs.map(
          (glob) => `${workspaceRoot}${glob}/**/*.page.ts`,
        ),
      ],
      { dot: true, absolute: true },
    ).map((file) => {
      const normalized = normalizePath(file);
      return normalized.startsWith(root)
        ? normalized.replace(root, '')
        : normalized;
    });
  }

  function discoverContentFiles(): string[] {
    return globSync(
      [
        `${root}/src/app/routes/**/*.md`,
        `${root}/src/app/pages/**/*.md`,
        `${root}/src/content/**/*.md`,
        ...resolvedOptions.additionalContentDirs.map(
          (glob) => `${workspaceRoot}${glob}/**/*.md`,
        ),
      ],
      { dot: true, absolute: true },
    ).map((file) => {
      const normalized = normalizePath(file);
      return normalized.startsWith(root)
        ? normalized.replace(root, '')
        : normalized;
    });
  }

  function buildEntries(): JsonLdManifestEntry[] {
    const entries: JsonLdManifestEntry[] = [];
    let importIndex = 0;

    discoverRouteFiles().forEach((filename) => {
      try {
        const source = readFileSync(join(root, filename), 'utf-8');
        if (!detectJsonLdModuleExports(source)) {
          return;
        }

        entries.push({
          kind: 'module',
          routePath: filenameToRoutePath(filename),
          sourceFile: filename,
          importAlias: `routeModule${importIndex++}`,
        });
      } catch {
        // ignore unreadable route file
      }
    });

    discoverContentFiles().forEach((filename) => {
      try {
        const source = readFileSync(join(root, filename), 'utf-8');
        const jsonLd = extractMarkdownJsonLd(source);

        if (jsonLd.length === 0) {
          return;
        }

        entries.push({
          kind: 'content',
          routePath: filenameToRoutePath(filename),
          sourceFile: filename,
          jsonLd,
        });
      } catch {
        // ignore unreadable content file
      }
    });

    return entries.sort((a, b) => a.routePath.localeCompare(b.routePath));
  }

  function generate(): void {
    const entries = buildEntries();
    const source = generateJsonLdManifestSource(
      entries,
      resolvedOptions.outFile,
    );
    const outPath = join(root, resolvedOptions.outFile);
    const outDir = dirname(outPath);

    if (!existsSync(outDir)) {
      mkdirSync(outDir, { recursive: true });
    }

    let existing = '';
    try {
      existing = readFileSync(outPath, 'utf-8');
    } catch {
      // file does not exist yet
    }

    if (existing !== source) {
      writeFileSync(outPath, source, 'utf-8');
    }
  }

  function isRouteFile(path: string): boolean {
    const normalized = normalizePath(path);
    return (
      (normalized.includes('/routes/') ||
        normalized.includes('/pages/') ||
        normalized.includes('/content/')) &&
      (normalized.endsWith('.ts') || normalized.endsWith('.md'))
    );
  }

  return {
    name: 'analog-json-ld-manifest',
    config(config) {
      root = normalizePath(resolve(workspaceRoot, config.root || '.') || '.');
    },
    buildStart() {
      generate();
    },
    configureServer(server) {
      const regenerate = (path: string) => {
        if (isRouteFile(path)) {
          generate();
        }
      };

      server.watcher.on('add', regenerate);
      server.watcher.on('change', regenerate);
      server.watcher.on('unlink', regenerate);
    },
  };
}

function toImportPath(outFile: string, sourceFile: string): string {
  const fromDir = dirname(outFile);
  const sourceNoExt = sourceFile
    .replace(/^\//, '')
    .replace(/\.(ts|js|analog|ag)$/, '');
  const relativePath = normalizePath(relative(fromDir, sourceNoExt));

  if (relativePath.startsWith('.')) {
    return relativePath;
  }

  return `./${relativePath}`;
}
