/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/about': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/about.page').routeMeta;
    };
    '/admin': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/admin.page').routeMeta;
    };
    '/admin/dashboard': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [typeof import('./app/pages/admin.page').routeMeta];
      routeMeta: typeof import('./app/pages/admin/dashboard.page').routeMeta;
    };
    '/admin/settings': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [typeof import('./app/pages/admin.page').routeMeta];
      routeMeta: typeof import('./app/pages/admin/settings.page').routeMeta;
    };
    '/pricing': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [
        typeof import('./app/pages/(marketing).page').routeMeta,
      ];
      routeMeta: typeof import('./app/pages/(marketing)/pricing.page').routeMeta;
    };
    '/search': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/users': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/orgs/[orgId]': {
      params: { orgId: string };
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/orgs/[orgId].page').routeMeta;
      load: typeof import('./app/pages/orgs/[orgId].server').load;
    };
    '/orgs/[orgId]/teams/[teamId]': {
      params: { orgId: string; teamId: string };
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [
        typeof import('./app/pages/orgs/[orgId].page').routeMeta,
      ];
      routeMeta: typeof import('./app/pages/orgs/[orgId]/teams/[teamId].page').routeMeta;
    };
    '/orgs/[orgId]/teams/[teamId]/members': {
      params: { orgId: string; teamId: string };
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [
        typeof import('./app/pages/orgs/[orgId].page').routeMeta,
        typeof import('./app/pages/orgs/[orgId]/teams/[teamId].page').routeMeta,
      ];
    };
    '/orgs/[orgId]/teams/[teamId]/members/[memberId]': {
      params: { orgId: string; teamId: string; memberId: string };
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [
        typeof import('./app/pages/orgs/[orgId].page').routeMeta,
        typeof import('./app/pages/orgs/[orgId]/teams/[teamId].page').routeMeta,
      ];
      routeMeta: typeof import('./app/pages/orgs/[orgId]/teams/[teamId]/members/[memberId].page').routeMeta;
      load: typeof import('./app/pages/orgs/[orgId]/teams/[teamId]/members/[memberId].server').load;
    };
    '/users/[userId]': {
      params: { userId: string };
      query: Record<string, string | string[] | undefined>;
      layoutRouteMeta: [typeof import('./app/pages/users.page').routeMeta];
      routeMeta: typeof import('./app/pages/users/[userId].page').routeMeta;
      load: typeof import('./app/pages/users/[userId].server').load;
    };
    '/users/[userId]/posts/[postId]': {
      params: { userId: string; postId: string };
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/users.[userId].posts.[postId].page').routeMeta;
    };
    '/docs/[...slug]': {
      params: { slug: string[] };
      query: Record<string, string | string[] | undefined>;
    };
    '/files/[[...path]]': {
      params: { path?: string[] };
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
