// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guide': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guide/getting-started': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/intro': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/reference/api/nested/path': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      paramsOutput: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
