/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      routeMeta: typeof import('./app/pages/index.page').routeMeta;
    };
    '/docs': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/guide': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/guide/getting-started': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/intro': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/reference/api/nested/path': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
