// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guide': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/guide/getting-started': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/intro': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/reference/api/nested/path': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/docs/[[...slug]]': {
      params: { slug?: string[] };
      paramsOutput: { slug?: string[] };
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/index": AnalogGeneratedRouteRecord<"/index", "/", "/", null, readonly []>;
  "/docs": AnalogGeneratedRouteRecord<"/docs", "docs", "/docs", null, readonly ["/docs/guide/index", "/docs/intro", "/docs/reference/api/nested/path", "/docs/[[...slug]]"]>;
  "/docs/guide/index": AnalogGeneratedRouteRecord<"/docs/guide/index", "guide", "/docs/guide", "/docs", readonly ["/docs/guide/getting-started"]>;
  "/docs/guide/getting-started": AnalogGeneratedRouteRecord<"/docs/guide/getting-started", "getting-started", "/docs/guide/getting-started", "/docs/guide/index", readonly []>;
  "/docs/intro": AnalogGeneratedRouteRecord<"/docs/intro", "intro", "/docs/intro", "/docs", readonly []>;
  "/docs/reference/api/nested/path": AnalogGeneratedRouteRecord<"/docs/reference/api/nested/path", "reference/api/nested/path", "/docs/reference/api/nested/path", "/docs", readonly []>;
  "/docs/[[...slug]]": AnalogGeneratedRouteRecord<"/docs/[[...slug]]", "[[...slug]]", "/docs/[[...slug]]", "/docs", readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/index"];
  "/docs": AnalogFileRoutesById["/docs"];
  "/docs/guide": AnalogFileRoutesById["/docs/guide/index"];
  "/docs/guide/getting-started": AnalogFileRoutesById["/docs/guide/getting-started"];
  "/docs/intro": AnalogFileRoutesById["/docs/intro"];
  "/docs/reference/api/nested/path": AnalogFileRoutesById["/docs/reference/api/nested/path"];
  "/docs/[[...slug]]": AnalogFileRoutesById["/docs/[[...slug]]"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/index": {
      id: "/index",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/index.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/index"],
    "/docs": {
      id: "/docs",
      path: "docs",
      fullPath: "/docs",
      parentId: null,
      children: ["/docs/guide/index", "/docs/intro", "/docs/reference/api/nested/path", "/docs/[[...slug]]"] as const,
      sourceFile: "/src/app/pages/docs.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs"],
    "/docs/guide/index": {
      id: "/docs/guide/index",
      path: "guide",
      fullPath: "/docs/guide",
      parentId: "/docs",
      children: ["/docs/guide/getting-started"] as const,
      sourceFile: "/src/content/docs/guide/index.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: true,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guide/index"],
    "/docs/guide/getting-started": {
      id: "/docs/guide/getting-started",
      path: "getting-started",
      fullPath: "/docs/guide/getting-started",
      parentId: "/docs/guide/index",
      children: [] as const,
      sourceFile: "/src/content/docs/guide/getting-started.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/guide/getting-started"],
    "/docs/intro": {
      id: "/docs/intro",
      path: "intro",
      fullPath: "/docs/intro",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/intro.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/intro"],
    "/docs/reference/api/nested/path": {
      id: "/docs/reference/api/nested/path",
      path: "reference/api/nested/path",
      fullPath: "/docs/reference/api/nested/path",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/content/docs/reference/api/nested/path.md",
      kind: "content",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/docs/reference/api/nested/path"],
    "/docs/[[...slug]]": {
      id: "/docs/[[...slug]]",
      path: "[[...slug]]",
      fullPath: "/docs/[[...slug]]",
      parentId: "/docs",
      children: [] as const,
      sourceFile: "/src/app/pages/docs/[[...slug]].page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: true,
    } satisfies AnalogFileRoutesById["/docs/[[...slug]]"],
  },
  byFullPath: {
    "/": "/index",
    "/docs": "/docs",
    "/docs/guide": "/docs/guide/index",
    "/docs/guide/getting-started": "/docs/guide/getting-started",
    "/docs/intro": "/docs/intro",
    "/docs/reference/api/nested/path": "/docs/reference/api/nested/path",
    "/docs/[[...slug]]": "/docs/[[...slug]]",
  },
} as const;
