/**
 * Auto-generated by @analogjs/platform
 * Run `npm run dev` or `npm run build` to regenerate.
 * DO NOT EDIT MANUALLY
 */

import type { Signal } from '@angular/core';
import type {
  NavigationExtras,
  NavigationBehaviorOptions,
} from '@angular/router';
import type {
  TypeConstructor,
  InferConstructor,
  SchemaLike,
  InferSchemaOutput,
} from '@analogjs/router';

declare module '@analogjs/router' {
  /** Static routes (no parameters required) */
  export type StaticRoutes =
    | '/'
    | '/about-me'
    | '/cart'
    | '/client'
    | '/newsletter'
    | '/package'
    | '/search'
    | '/server'
    | '/shipping'
    | '/sign-up'
    | '/test';

  /** Dynamic route parameter types (for building routes) */
  export interface DynamicRouteParams {
    '/[...slug]': { slug: string | number };
    '/blog/[slug]': { slug: string | number };
    '/products/[productId]': { productId: string | number };
    '/shipping/[...slug]': { slug: string | number };
  }

  /** Resolved parameter types (runtime values are strings) */
  export interface ResolvedRouteParams {
    '/[...slug]': { slug: string };
    '/blog/[slug]': { slug: string };
    '/products/[productId]': { productId: string };
    '/shipping/[...slug]': { slug: string };
  }

  /** Dynamic routes (parameters required) */
  export type DynamicRoutes = keyof DynamicRouteParams;

  /** All valid application routes */
  export type TypedRoutes = StaticRoutes | DynamicRoutes;

  /**
   * Override the base TypedRoute to allow valid routes.
   * The base package uses 'never' to force generation of this file.
   */
  export type TypedRoute = TypedRoutes;

  /** Extract parameter type for building a route */
  export type RouteParams<T extends DynamicRoutes> = DynamicRouteParams[T];

  /** Extract resolved parameter type for consuming route params */
  export type ResolvedParams<T extends DynamicRoutes> = ResolvedRouteParams[T];

  /** Build a typed route path */
  export function route<T extends StaticRoutes>(path: T): T;
  export function route<T extends DynamicRoutes>(
    path: T,
    params: DynamicRouteParams[T],
  ): string;

  /** Type-safe navigation (wrapper for Router.navigate) */
  export function navigate<T extends StaticRoutes>(
    path: T,
    params?: undefined,
    extras?: NavigationExtras,
  ): Promise<boolean>;
  export function navigate<T extends DynamicRoutes>(
    path: T,
    params: DynamicRouteParams[T],
    extras?: NavigationExtras,
  ): Promise<boolean>;

  /** Type-safe URL navigation (wrapper for Router.navigateByUrl) */
  export function navigateByUrl<T extends StaticRoutes>(
    path: T,
    params?: undefined,
    extras?: NavigationBehaviorOptions,
  ): Promise<boolean>;
  export function navigateByUrl<T extends DynamicRoutes>(
    path: T,
    params: DynamicRouteParams[T],
    extras?: NavigationBehaviorOptions,
  ): Promise<boolean>;

  /** Inject typed route params as a Signal */
  export function injectParams<T extends DynamicRoutes>(): Signal<
    ResolvedRouteParams[T]
  >;

  /** Inject typed route params with schema override */
  export function injectParams<
    T extends DynamicRoutes,
    S extends
      | { [K in keyof ResolvedRouteParams[T]]?: TypeConstructor }
      | SchemaLike<unknown>,
  >(
    schema: S,
  ): Signal<
    S extends SchemaLike<unknown>
      ? InferSchemaOutput<S>
      : {
          [K in keyof ResolvedRouteParams[T]]: K extends keyof S
            ? S[K] extends TypeConstructor
              ? InferConstructor<S[K]>
              : string
            : string;
        }
  >;
}
