/**
 * Auto-generated by @analogjs/platform
 * Run `npm run dev` or `npm run build` to regenerate.
 * DO NOT EDIT MANUALLY
 */

import type {
  NavigationExtras,
  NavigationBehaviorOptions,
} from '@angular/router';

declare module '@analogjs/router' {
  /** Static routes (no parameters required) */
  export type StaticRoutes =
    | '/'
    | '/about-me'
    | '/cart'
    | '/client'
    | '/newsletter'
    | '/package'
    | '/search'
    | '/server'
    | '/shipping'
    | '/sign-up'
    | '/test';

  /** Dynamic route parameter types (for building routes) */
  export interface DynamicRouteParams {
    '/[...slug]': { slug: string | number };
    '/blog/[slug]': { slug: string | number };
    '/products/[productId]': { productId: string | number };
    '/shipping/[...slug]': { slug: string | number };
  }

  /**
   * Augment ResolvedRouteParams with application routes.
   * This interface is merged with the empty base interface from @analogjs/router.
   */
  export interface ResolvedRouteParams {
    '/[...slug]': { slug: string };
    '/blog/[slug]': { slug: string };
    '/products/[productId]': { productId: string };
    '/shipping/[...slug]': { slug: string };
  }

  /** All valid application routes */
  export type TypedRoutes = StaticRoutes | keyof DynamicRouteParams;

  /** Override the base TypedRoute to allow valid routes */
  export type TypedRoute = TypedRoutes;

  /** Extract parameter type for building a route */
  export type RouteParams<T extends keyof DynamicRouteParams> =
    DynamicRouteParams[T];

  /** Extract resolved parameter type for consuming route params */
  export type ResolvedParams<T extends keyof ResolvedRouteParams> =
    ResolvedRouteParams[T];

  /** Build a typed route path */
  export function route<T extends StaticRoutes>(path: T): T;
  export function route<T extends keyof DynamicRouteParams>(
    path: T,
    params: DynamicRouteParams[T],
  ): string;

  /** Type-safe navigation (wrapper for Router.navigate) */
  export function navigate<T extends StaticRoutes>(
    path: T,
    params?: undefined,
    extras?: NavigationExtras,
  ): Promise<boolean>;
  export function navigate<T extends keyof DynamicRouteParams>(
    path: T,
    params: DynamicRouteParams[T],
    extras?: NavigationExtras,
  ): Promise<boolean>;

  /** Type-safe URL navigation (wrapper for Router.navigateByUrl) */
  export function navigateByUrl<T extends StaticRoutes>(
    path: T,
    params?: undefined,
    extras?: NavigationBehaviorOptions,
  ): Promise<boolean>;
  export function navigateByUrl<T extends keyof DynamicRouteParams>(
    path: T,
    params: DynamicRouteParams[T],
    extras?: NavigationBehaviorOptions,
  ): Promise<boolean>;
}
