/** @noprettier */
// This file is auto-generated by @analogjs/platform
import type {} from '@analogjs/router';
declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-infinite': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-load': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      load: typeof import('./app/pages/tanstack-query-load.server').load;
    };
    '/tanstack-query-multi': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-optimistic': {
      params: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
    };
  }
}

export {};
