// This file is auto-generated by @analogjs/platform
// Do not edit manually

declare module '@analogjs/router' {
  interface AnalogRouteTable {
    '/': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-infinite': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-multi': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
    '/tanstack-query-optimistic': {
      params: Record<string, never>;
      paramsOutput: Record<string, never>;
      query: Record<string, string | string[] | undefined>;
      queryOutput: Record<string, string | string[] | undefined>;
    };
  }
}

export {};

export interface AnalogGeneratedRouteRecord<
  TId extends string = string,
  TPath extends string = string,
  TFullPath extends string = string,
  TParentId extends string | null = string | null,
  TChildren extends readonly string[] = readonly string[],
> {
  id: TId;
  path: TPath;
  fullPath: TFullPath;
  parentId: TParentId;
  children: TChildren;
  sourceFile: string;
  kind: 'page' | 'content';
  hasParamsSchema: boolean;
  hasQuerySchema: boolean;
  hasJsonLd: boolean;
  isIndex: boolean;
  isGroup: boolean;
  isCatchAll: boolean;
  isOptionalCatchAll: boolean;
}

export interface AnalogFileRoutesById {
  "/(home)": AnalogGeneratedRouteRecord<"/(home)", "/", "/", null, readonly []>;
  "/tanstack-query": AnalogGeneratedRouteRecord<"/tanstack-query", "tanstack-query", "/tanstack-query", null, readonly []>;
  "/tanstack-query-infinite": AnalogGeneratedRouteRecord<"/tanstack-query-infinite", "tanstack-query-infinite", "/tanstack-query-infinite", null, readonly []>;
  "/tanstack-query-multi": AnalogGeneratedRouteRecord<"/tanstack-query-multi", "tanstack-query-multi", "/tanstack-query-multi", null, readonly []>;
  "/tanstack-query-optimistic": AnalogGeneratedRouteRecord<"/tanstack-query-optimistic", "tanstack-query-optimistic", "/tanstack-query-optimistic", null, readonly []>;
}

export interface AnalogFileRoutesByFullPath {
  "/": AnalogFileRoutesById["/(home)"];
  "/tanstack-query": AnalogFileRoutesById["/tanstack-query"];
  "/tanstack-query-infinite": AnalogFileRoutesById["/tanstack-query-infinite"];
  "/tanstack-query-multi": AnalogFileRoutesById["/tanstack-query-multi"];
  "/tanstack-query-optimistic": AnalogFileRoutesById["/tanstack-query-optimistic"];
}

export type AnalogRouteTreeId = keyof AnalogFileRoutesById;
export type AnalogRouteTreeFullPath = keyof AnalogFileRoutesByFullPath;

export const analogRouteTree = {
  byId: {
    "/(home)": {
      id: "/(home)",
      path: "/",
      fullPath: "/",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/(home).page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: true,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/(home)"],
    "/tanstack-query": {
      id: "/tanstack-query",
      path: "tanstack-query",
      fullPath: "/tanstack-query",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/tanstack-query.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/tanstack-query"],
    "/tanstack-query-infinite": {
      id: "/tanstack-query-infinite",
      path: "tanstack-query-infinite",
      fullPath: "/tanstack-query-infinite",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/tanstack-query-infinite.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/tanstack-query-infinite"],
    "/tanstack-query-multi": {
      id: "/tanstack-query-multi",
      path: "tanstack-query-multi",
      fullPath: "/tanstack-query-multi",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/tanstack-query-multi.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/tanstack-query-multi"],
    "/tanstack-query-optimistic": {
      id: "/tanstack-query-optimistic",
      path: "tanstack-query-optimistic",
      fullPath: "/tanstack-query-optimistic",
      parentId: null,
      children: [] as const,
      sourceFile: "/src/app/pages/tanstack-query-optimistic.page.ts",
      kind: "page",
      hasParamsSchema: false,
      hasQuerySchema: false,
      hasJsonLd: false,
      isIndex: false,
      isGroup: false,
      isCatchAll: false,
      isOptionalCatchAll: false,
    } satisfies AnalogFileRoutesById["/tanstack-query-optimistic"],
  },
  byFullPath: {
    "/": "/(home)",
    "/tanstack-query": "/tanstack-query",
    "/tanstack-query-infinite": "/tanstack-query-infinite",
    "/tanstack-query-multi": "/tanstack-query-multi",
    "/tanstack-query-optimistic": "/tanstack-query-optimistic",
  },
} as const;
